feat(module:skeleton): add nzRound prop and skeleton-element image
NG-ZORRO/ng-zorro-antd pull request #5710
Opened 2020-08-25 02:08 UTC by yangjunhan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

Aim to sync with the latest Ant-design skeleton component. Ant-design relevant issues:

- feat: Skeleton add round prop (https://github.com/ant-design/ant-design/pull/24137)

- feat: add Skeleton-Image (https://github.com/ant-design/ant-design/pull/24805)

## What is the new behavior?

Show paragraph and title radius when nzRound is true.

Add new nz-skeleton-element [nzType="image"].

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-08-26 08:33 UTC, wenqi73 commented on components/skeleton/skeleton-element.component.ts
> +    'M984.615385 196.923077c0-43.323077-35.446154-78.769231-78.769231-78.769231H118.153846c-43.323077 0-78.769231 35.446154-78.769231 78.769231v630.153846c0 43.323077 35.446154 78.769231 78.769231 78
两边的图不一样，检查下

2020-08-26 08:35 UTC, wenqi73 commented
测试用例要加上

2020-08-27 07:44 UTC, vthinkxie requested changes
element 选项应当合并

2020-09-03 12:54 UTC, wenqi73 requested changes

2020-09-03 12:54 UTC, wenqi73 commented on components/skeleton/skeleton-element.component.ts
> +    'M365.714286 329.142857q0 45.714286-32.036571 77.677714t-77.677714 32.036571-77.677714-32.036571-32.036571-77.677714 32.036571-77.677714 77.677714-32.036571 77.677714 32.036571 32.036571 77.67771
```suggestion
    <span class="ant-skeleton-image">
      <svg class="ant-skeleton-image-svg" viewBox="0 0 1098 1024" xmlns="http://www.w3.org/2000/svg">
        <path d="M365.714286 329.142857q0 45.714286-32.036571 77.677714t-77.677714 32.036571-77.677714-32.036571-32.036571-77.677714 32.036571-77.677714 77.677714-32.036571 77.677714 32.036571 32.036571 77.677714zM950.857143 548.571429l0 256-804.571429 0 0-109.714286 182.857143-182.857143 91.428571 91.428571 292.571429-292.571429zM1005.714286 146.285714l-914.285714 0q-7.460571 0-12.873143 5.412571t-5.412571 12.873143l0 694.857143q0 7.460571 5.412571 12.873143t12.873143 5.412571l914.285714 0q7.460571 0 12.873143-5.412571t5.412571-12.873143l0-694.857143q0-7.460571-5.412571-12.873143t-12.873143-5.412571zM1097.142857 164.571429l0 694.857143q0 37.741714-26.843429 64.585143t-64.585143 26.843429l-914.285714 0q-37.741714 0-64.585143-26.843429t-26.843429-64.585143l0-694.857143q0-37.741714 26.843429-64.585143t64.585143-26.843429l914.285714 0q37.741714 0 64.585143 26.843429t26.843429 64.585143z" class="ant-skeleton-image-path" />
      </svg>
    </span>
  `
})
export class NzSkeletonElementImageComponent {
```

2020-09-10 07:40 UTC, merged