Pagination nzPageSizeOptions Global Configuration
NG-ZORRO/ng-zorro-antd pull request #6043
Opened 2020-11-11 09:43 UTC by Xie-Jay

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: [6042](https://github.com/NG-ZORRO/ng-zorro-antd/issues/6042)

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-11-11 09:52 UTC, vthinkxie requested changes
commit规范请遵循 angular commit format
例如 `feat(module:pagination): support nzPageSizeOptions global configuration`

代码实现部分也有一些建议，非常感谢提交代码

2020-11-11 09:52 UTC, vthinkxie commented on components/pagination/doc/index.zh-CN.md
> +### 全局配置
建议和其他组件的文档格式保持一致，在表格再增加一列是否支持全局

2020-11-11 09:52 UTC, vthinkxie commented on components/pagination/pagination.component.ts
> +  private onConfigChange(): void {
建议参照其他组件的 @WithConfig 用法，可以大幅度简化代码实现

2020-11-11 10:55 UTC, Xie-Jay commented on components/pagination/doc/index.zh-CN.md
> +### 全局配置
我没早到表格有支持全局的例子

2020-11-11 10:56 UTC, Xie-Jay commented on components/pagination/pagination.component.ts
> +  private onConfigChange(): void {
已做修改[1c160a69f947b9c033f08d1e958088288b169131](https://github.com/NG-ZORRO/ng-zorro-antd/pull/6043/commits/1c160a69f947b9c033f08d1e958088288b169131)

2020-11-21 06:53 UTC, hsuanxyz approved these changes

2020-11-21 06:54 UTC, merged