WIP feat(module: graph): support graph component
NG-ZORRO/ng-zorro-antd pull request #6053
Opened 2020-11-15 12:46 UTC by simplejason

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2020-11-16 00:44 UTC, vthinkxie commented on components/graph/core/minimap.ts
> +import * as d3 from 'd3';
不应当直接引入 d3， 这样不能treeshaking

2020-11-16 00:47 UTC, vthinkxie commented on components/graph/style/index.less
> +    right: 0px;
right: 0;

2020-11-16 00:47 UTC, vthinkxie commented on components/graph/doc/index.zh-CN.md
> +npm install d3-zoom
合并成一句

2020-11-16 00:49 UTC, vthinkxie commented on components/graph/core/minimap.ts
> +    d3.select(this.downloadCanvas).style('display', 'none');
import { select } from 'd3-selection';

2020-11-16 00:51 UTC, vthinkxie commented on components/graph/core/minimap.ts
> +    const drag = d3.drag().subject(Object).on('drag', handleEvent);
import { drag } from 'd3-drag';

2020-11-16 00:52 UTC, vthinkxie commented on components/graph/core/minimap.ts
> +    d3.select(this.svg).call(this.mainZoom.transform, d3.zoomIdentity.translate(mainX, mainY).scale(this.scaleMain));
import { zoomIdentity } from 'd3-zoom';

2020-11-16 00:53 UTC, vthinkxie commented on components/graph/graph-edge.directive.ts
> +    .curve(d3.curveBasis);
import { curveBasis } from 'd3-shape';

2020-11-16 00:53 UTC, vthinkxie commented on components/graph/graph-edge.directive.ts
> +    .line<{ x: number; y: number }>()
import { line } from 'd3-shape';

2020-11-16 00:53 UTC, vthinkxie commented on components/graph/core/minimap.ts
> +      const clickCoords = d3.pointer(event, minimapSvgElement.node() as NzSafeAny);
import { pointer } from 'd3-selection';

2020-11-16 00:54 UTC, vthinkxie commented on components/graph/core/minimap.ts
> +    downloadSelection.on('click', () => {
下载功能先不要增加

2020-11-16 01:00 UTC, vthinkxie commented on components/graph/graph.component.ts
> +// export const ROOT_NODE_NAME = '__root__';
无用代码不要注释，直接删掉

2020-11-21 03:55 UTC, hsuanxyz requested changes

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/core/minimap.ts
> +  zoom(transform?: ZoomTransform): void {
jsdoc 和参数不符

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/data-source/base-graph-source.ts
> + * User can also use it outside the `<cdk-tree>` to control the expansion status of the tree.
这里还是 cdk-tree 的注释

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/data-source/graph-data-source.ts
> +  _data = new BehaviorSubject<NzGraphDataDef>({} as NzGraphDataDef);
这里是 private

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/data-source/graph-data-source.ts
> +  dataSource!: NzGraphDataDef;
constructor 构造参数是可选的，这里类型不安全

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/data-source/graph-data-source.ts
> +  /** A selection model with multi-selection to track expansion status. */
为什么有 2 条 jdcos

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/data-source/graph-data-source.ts
> +   */
这条注释没用

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/data-source/graph-data-source.ts
> +  setData(data: NzGraphDataDef): void {
expansionModel 需要重置吗？

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/demo/customized.ts
> +  dataSource = new NzGraphData(this.testDef);
```suggestion
  graphData = new NzGraphData(this.testDef);
```

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/doc/index.en-US.md
> +#### NzGraphGroupNode
NzGraphGroupNode NzGraphEdge NzGraphNode 现在在哪里访问，怎么访问，文档上没写出来

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/doc/index.zh-CN.md
> +subtitle: 层次图
中文有没有更好的?

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph-minimap.component.ts
> +  zoomInit$ = new Subscription();
没有地方使用这个成员

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph-node.directive.ts
> +  @HostListener('click', ['$event'])
移到 @Directive({host}) 吧

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph.component.ts
> +    <ng-content></ng-content>
content 有用吗？

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph.component.ts
> +  static ngAcceptInputType_nzAutoSize: BooleanInput;
文档和 API 不一致

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph.component.ts
> +  autoLayout(): void {
这里 layout render fit 概念混淆了

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph.component.ts
> +    if (isDataSource(this.dataSource)) {
为什么没在初始化是判断？

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph.component.ts
> +      throw Error(`A valid data source must be provided.`);
既然已经在 ngAfterContentChecked 中检查了，这里为什么还要抛错

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph.component.ts
> +    this.cdr.detectChanges();
动画完了再 detectChanges？

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/interface.ts
> +    duration: 250
animatonBuilder 中没有使用这块配置

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/doc/index.en-US.md
> +npm install @nx-component/hierarchy-graph && npm install d3
npm install d3-* @types/d3

2020-11-21 03:55 UTC, hsuanxyz commented on components/graph/graph.component.ts
> +            const targetNode = flattenNodes(renderInfo).find(n => `${n.name}` === nodeEle.id);
改成 deepFind， flattenNodes 每次都是全量循环

2020-11-21 04:15 UTC, simplejason commented on components/graph/graph.component.ts
> +    <ng-content></ng-content>
给自定义节点使用

2020-11-21 04:17 UTC, simplejason commented on components/graph/graph.component.ts
> +  autoLayout(): void {
改为autoFit 自适配

2020-11-21 04:31 UTC, simplejason commented on components/graph/graph.component.ts
> +            const targetNode = flattenNodes(renderInfo).find(n => `${n.name}` === nodeEle.id);
部分暂时不改了，下个版本一起做掉，这个rc版本先内部试用

2020-11-21 06:28 UTC, hsuanxyz approved these changes

2020-11-21 06:29 UTC, merged