Dep s/time placeholder i18n
NG-ZORRO/ng-zorro-antd pull request #6069
Opened 2020-11-18 14:03 UTC by DepickereSven

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
When you update the ``i18n.setLocale()`` after a few seconds the placeholder of the ``time-picker component`` will not update. 

Reproduce https://stackblitz.com/edit/angular-qyneqn?file=src/app/app.component.ts

## What is the new behavior?
Whenever you update ``i18n.setLocale()`` the placeholder will also update.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-12-14 12:59 UTC, DepickereSven commented
@wenqi73 is it possible to review this PR because it's an annoying bug that the language isn't correct when you reload the page.

2020-12-15 02:19 UTC, wenqi73 requested changes
Thanks for your contribution, add a unit test example would be better.

2020-12-15 02:19 UTC, wenqi73 commented on components/time-picker/time-picker.component.ts
> +    );
```suggestion
    this.i18nPlaceHolder$ = this.i18n.localeChange.pipe(
      map((nzLocale: NzI18nInterface) => nzLocale.TimePicker.placeholder)
    );
```
Already has the initial value, no need to use `startWith`.

2020-12-15 10:24 UTC, DepickereSven commented
@wenqi73 I added a test case for the change I made. 
But I had also a merge conflict to solve.
I resolved the merge conflict with a merge from master and now I have a lot of file changes.
But they are formatting changes, do I need to create a new PR or is it okay like this?

2020-12-15 11:15 UTC, wenqi73 commented on components/time-picker/time-picker.component.spec.ts
> +  }
```suggestion

```

2020-12-15 11:15 UTC, wenqi73 commented on components/time-picker/time-picker.component.spec.ts
> +  i18nPlaceHolder$: Observable<string | undefined> = of(undefined);
```suggestion

```

2020-12-15 11:16 UTC, wenqi73 commented on components/time-picker/time-picker.component.spec.ts
> +      [nzPlaceHolder]="i18nPlaceHolder$ | async"
```suggestion
```

2020-12-15 11:18 UTC, wenqi73 commented on components/time-picker/time-picker.component.spec.ts
> +        expect(placeHolderValue).toBe('请选择时间');
```
placeholder = timeElement.nativeElement.querySelector('input').placeholder;
```

2020-12-15 11:21 UTC, wenqi73 commented
@DepickereSven The formatting change is OK, no need to change this.

2020-12-15 12:56 UTC, wenqi73 approved these changes
Thanks @DepickereSven !

2020-12-15 12:57 UTC, merged

2020-12-15 13:03 UTC, DepickereSven commented
@wenqi73 You're welcome and thank you for reviewing!