feat(module:image): add image component
NG-ZORRO/ng-zorro-antd pull request #6154
Opened 2020-12-06 12:04 UTC by stygian-desolator

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information
WIP, pls mark as draft, thanks~

2020-12-12 10:39 UTC, stygian-desolator commented
@hsuanxyz cc, thanks~

2020-12-13 07:36 UTC, hsuanxyz requested changes
Good work!

2020-12-13 07:36 UTC, hsuanxyz commented on components/image/image-preview.component.ts
> +      icon: 'close',
The icons here need to be imported statically in `components/icon/icons.ts`

2020-12-13 07:36 UTC, hsuanxyz commented on components/image/doc/index.en-US.md
> +| close | Close image preview | `() => void` | - |
```suggestion
| Name | Description |
| --- | --- |
| active(index: number): void | Set active index |
| prev(): void | Previous image |
| next(): void | Next image |
| close(): void | Close image preview |
```

2020-12-13 07:36 UTC, hsuanxyz commented on components/image/doc/index.zh-CN.md
> +| close | 关闭预览 | `() => void` | - |
```suggestion
| 名称 | 描述 |
| --- | --- |
| active(index: number): void | 设置预览索引 |
| prev(): void | 上一张 |
| next(): void | 下一张 |
| close(): void | 关闭预览 |
```

2020-12-13 12:30 UTC, stygian-desolator commented
@hsuanxyz  Please review again, thanks~

2020-12-15 03:18 UTC, hsuanxyz commented
@stygian-desolator The fit-content action is only applied when the visible area is not completely covered.

![image](https://user-images.githubusercontent.com/22736418/102166523-398eb580-3ec7-11eb-9e15-bd4428dce3e5.png)

2020-12-15 11:23 UTC, merged