feat(module:tree-view): add tree-view component
NG-ZORRO/ng-zorro-antd pull request #6161
Opened 2020-12-08 03:44 UTC by hsuanxyz

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: close #5976, close #5809, close #5739, close #5736, close #5519, close #5446, close #5152, close #4694, close #4472, close #3832, close #2785, close #2744

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-12-08 07:12 UTC, yangjunhan reviewed
Document translation modifications.

2020-12-08 07:12 UTC, yangjunhan commented on components/tree-view/doc/index.en-US.md
> +Does not do anything to the toggle section, available with a placeholder or display icons.
```suggestion
A toggle that does no actions. This can be used for placeholders or displays icons.
```

2020-12-08 07:12 UTC, yangjunhan commented on components/tree-view/doc/index.en-US.md
> +Toggle part, used to expand / collapse the node.
```suggestion
A toggle which is used to expand / collapse the node.
```

2020-12-08 07:12 UTC, yangjunhan commented on components/tree-view/doc/index.en-US.md
> +Define icons in the toggle part, which will automatically rotate with the collapse/expand state.
```suggestion
Define an icon in the toggle, which it will automatically rotate depending on the collapse/expand state.
```

2020-12-08 07:12 UTC, yangjunhan commented on components/tree-view/doc/index.en-US.md
> +Defines the icons in the toggle section to have an active style, which can be used for loading icon.
```suggestion
Defines an icon in the toggle for an active style, which it  can be used for the loading state.
```

2020-12-08 07:12 UTC, yangjunhan commented on components/tree-view/doc/index.en-US.md
> +Defines the selectable part of a node.
```suggestion
Defines the selectable feature of a node.
```

2020-12-08 07:12 UTC, yangjunhan commented on components/tree-view/doc/index.en-US.md
> +Defines the checkable parts of a node.
```suggestion
Defines the checkbox feature of a node.
```

2020-12-08 07:12 UTC, yangjunhan commented on components/tree-view/doc/index.zh-CN.md
> +不做任何操作的切换部分，可用与占位或者显示图标。
```suggestion
不做任何操作的切换部分，可用于占位或者显示图标。
```

2020-12-14 04:02 UTC, simplejason requested changes

2020-12-14 05:20 UTC, hsuanxyz commented on components/tree-view/tree-view.ts
> +    Promise.resolve().then(() => {
Yes, in `ngAfterViewInit`

2020-12-14 05:24 UTC, hsuanxyz commented on components/tree-view/style/index.less
> +  -webkit-overflow-scrolling: touch;
this is patch for CDK.

2020-12-16 05:14 UTC, simplejason approved these changes

2020-12-16 05:15 UTC, merged