feat(module:popconfirm): support nzAutoFocus
NG-ZORRO/ng-zorro-antd pull request #6256
Opened 2020-12-24 03:51 UTC by yangjunhan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #6249 

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-01-03 09:29 UTC, wendellhu95 commented on components/tooltip/base.ts
> +  destroy$ = new Subject<void>();
Make this property as `protected`.

2021-02-13 12:53 UTC, vthinkxie requested changes
Hi @yangjunhan
@wendellhu95 has left some comments, could you have a look?
thanks

2021-06-10 11:47 UTC, hsuanxyz requested changes

2021-06-10 11:47 UTC, hsuanxyz commented on components/popconfirm/popconfirm.ts
> +    combineLatest([this.okBtn.changes, this.cancelBtn.changes])
use cdk/focusTrap

2021-06-11 07:25 UTC, yangjunhan commented on components/tooltip/base.ts
> +  destroy$ = new Subject<void>();
done

2021-06-11 07:25 UTC, yangjunhan commented on components/popconfirm/popconfirm.ts
> +    combineLatest([this.okBtn.changes, this.cancelBtn.changes])
done

2021-06-11 07:59 UTC, hsuanxyz approved these changes
LGTM

2021-06-11 07:59 UTC, merged