carousel(#5694) (#6355)
NG-ZORRO/ng-zorro-antd pull request #6356
Opened 2021-01-20 04:50 UTC by Xie-Jay

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: resolve #5694, #6355

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-01-21 01:40 UTC, Xie-Jay commented
some error with request check

![image](https://user-images.githubusercontent.com/64340763/105268039-93705280-5bcc-11eb-9d9d-c1b7eba80d22.png)

2021-01-22 07:39 UTC, vthinkxie requested changes
Hi, thanks a lot for the PR
some ci has failed, could you rebase onto master and try again?

2021-02-13 13:02 UTC, vthinkxie requested changes

2021-02-13 13:02 UTC, vthinkxie commented on components/carousel/carousel.component.ts
> +          this.cdr.detectChanges();
`this.cdr.detectChanges();`
should also be updated when the `isDragging` is false

2022-01-14 05:21 UTC, closed without merging