feat(module:time-picker,select,tree-select): support `nzId`
NG-ZORRO/ng-zorro-antd pull request #6379
Opened 2021-01-25 08:16 UTC by cipchk

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-02-13 13:08 UTC, vthinkxie requested changes

2021-02-13 13:08 UTC, vthinkxie commented on components/select/select-top-control.component.ts
> +  @Input() id: string | null = null;
should be `nzId`?
otherwise, there would be two same ids in the document

2021-02-25 12:20 UTC, hsuanxyz commented
@cipchk 代码冲突了

2021-02-25 13:11 UTC, cipchk commented
> @cipchk 代码冲突了

已处理。

2021-02-26 02:14 UTC, hsuanxyz approved these changes

2021-02-26 02:14 UTC, merged