fix: nz-upload drag drop will open new tab when use firefox versions …
NG-ZORRO/ng-zorro-antd pull request #7190
Opened 2022-01-05 12:33 UTC by small-lady

…91 and 92

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
解决nz-upload在火狐浏览器91及92版本上拖拽上传时会默认打开一个新窗口

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information

2022-01-06 15:21 UTC, arturovt requested changes

2022-01-06 15:21 UTC, arturovt commented on components/upload/upload.component.ts
> +  }
```suggestion
  constructor(private ngZone: NgZone, @Inject(DOCUMENT) private document: Document) {}

  ngAfterViewInit(): void {
    this.ngZone.runOutsideAngular(() => fromEvent(this.document.body, 'drop').pipe(takeUntil(this.destroy$)).subscribe(event => {
      event.preventDefault();
      event.stopPropagation();
    }));
  }
```

2022-01-06 15:21 UTC, arturovt commented on components/upload/upload.component.ts
> +    document.body.removeEventListener('drop', this.handleDropOpenNewTab)
```suggestion

```

2022-01-06 15:21 UTC, arturovt commented on components/upload/upload.component.ts
> +
```suggestion
```

2022-01-15 08:27 UTC, cipchk commented
@small-lady Record a screen? I don't see this prompt here. My firefox env: Mac 95.0.2 (64-bit).

2022-01-21 05:56 UTC, small-lady commented
> @small-lady Record a screen? I don't see this prompt here. My firefox env: Mac 95.0.2 (64-bit).

This problem is not in 95.0.2

2022-03-03 03:47 UTC, simplejason commented
> > @small-lady Record a screen? I don't see this prompt here. My firefox env: Mac 95.0.2 (64-bit).
> 
> This problem is not in 95.0.2 @cipchk ； it is in 91 and 92(Firefox Extended Support Release)

@cipchk Any question about this PR?

2022-03-04 11:51 UTC, cipchk requested changes

2022-03-04 11:51 UTC, cipchk commented on components/upload/upload.component.ts
> +    @Inject(DOCUMENT) private document: Document,
```suggestion
    @Inject(DOCUMENT) private document: NzSafeAny,
```

建议使用 `NzSafeAny` 来代替，不然可能在 SSR 下会有问题。

2022-03-04 13:22 UTC, small-lady commented on components/upload/upload.component.ts
> +    @Inject(DOCUMENT) private document: Document,
@cipchk 已按建议修改，谢谢~

2022-03-05 06:00 UTC, cipchk commented
LGTM

2022-03-21 02:37 UTC, merged