chore(release): release 13.0.1
NG-ZORRO/ng-zorro-antd pull request #7215
Opened 2022-01-18 08:43 UTC by simplejason

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2022-01-18 09:05 UTC, hsuanxyz requested changes

2022-01-18 09:05 UTC, hsuanxyz commented on CHANGELOG.md
> +* ***:** add tsconfig noImplicitOverride ([#7149](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7149)) ([806f024](https://github.com/NG-ZORRO/ng-zorro-antd/commit/806f024933aa4178cbfd6fa8a231b9a4b
这条不算在 perf

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.en-US.md
> +* ***:** add tsconfig noImplicitOverride ([#7149](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7149)) ([806f024](https://github.com/NG-ZORRO/ng-zorro-antd/commit/806f024933aa4178cbfd6fa8a231b9a4b
这条不算在 perf

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.zh-CN.md
> +* **drawer:** 修复 Title 为空时关闭图标的位置错误问题 ([#7176](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7176)) ([a6195b9](https://github.com/NG-ZORRO/ng-zorro-antd/commit/a6195b991a531e914faef2237dadf7226b8d
```suggestion
* **drawer:** 修复 `nzTitle` 为空时关闭图标的位置错误问题 ([#7176](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7176)) ([a6195b9](https://github.com/NG-ZORRO/ng-zorro-antd/commit/a6195b991a531e914faef2237dadf7226b8d6390)), closes [#7164](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7164)
```

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.zh-CN.md
> +* **tree-view:** 修复内部 trackBy 方法在虚拟滚动场景下节点异常问题 ([#7150](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7150)) ([4484674](https://github.com/NG-ZORRO/ng-zorro-antd/commit/4484674e212f67dea3aad8b56f2
```suggestion
* **tree-view:** 修复 trackBy 方法在虚拟滚动场景下节点异常问题 ([#7150](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7150)) ([4484674](https://github.com/NG-ZORRO/ng-zorro-antd/commit/4484674e212f67dea3aad8b56f27e9de61e6d21e)), closes [#7118](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7118)
```

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.zh-CN.md
> +* ***:** 添加 tsconfig noImplicitOverride 配置 ([#7149](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7149)) ([806f024](https://github.com/NG-ZORRO/ng-zorro-antd/commit/806f024933aa4178cbfd6fa8a231b9a
这条不算在 perf

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.zh-CN.md
> +* **back-top:** 增强 scrolling listener 健壮性 ([#7208](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7208)) ([3bcd343](https://github.com/NG-ZORRO/ng-zorro-antd/commit/3bcd343e38aefc35af1c2386a539d19a
这是 fix 不是 perf

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.en-US.md
> +* **back-top:** fix more reliable scrolling listener ([#7208](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7208)) ([3bcd343](https://github.com/NG-ZORRO/ng-zorro-antd/commit/3bcd343e38aefc35af1c2
这是 fix 不是 perf

2022-01-18 09:05 UTC, hsuanxyz commented on CHANGELOG.md
> +* **back-top:** fix more reliable scrolling listener ([#7208](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7208)) ([3bcd343](https://github.com/NG-ZORRO/ng-zorro-antd/commit/3bcd343e38aefc35af1c2
这是 fix 不是 perf

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.zh-CN.md
> +* **statistic:** `nzCountdownFinish` 事件触发后重新进入 ngZone ([#7137](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7137)) ([6835544](https://github.com/NG-ZORRO/ng-zorro-antd/commit/68355448198b31d9a064
这是 fix 不是 perf

2022-01-18 09:05 UTC, hsuanxyz commented on docs/changelog.en-US.md
> +* **statistic:** re-enter the Angular zone when the `nzCountdownFinish` emits ([#7137](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7137)) ([6835544](https://github.com/NG-ZORRO/ng-zorro-antd/com
这是 fix 不是 perf

2022-01-18 09:05 UTC, hsuanxyz commented on CHANGELOG.md
> +* **statistic:** re-enter the Angular zone when the `nzCountdownFinish` emits ([#7137](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7137)) ([6835544](https://github.com/NG-ZORRO/ng-zorro-antd/com
这是 fix 不是 perf

2022-01-18 10:46 UTC, hsuanxyz approved these changes

2022-01-18 10:47 UTC, merged

2022-01-20 08:05 UTC, qyjs commented
@hsuanxyz  The latest version is 13.0.1. Open nz-drawer and close the icon on the left.

i need open nz-drawer and close the icon on the right.

2022-01-21 02:19 UTC, yangjunhan commented
> i need open nz-drawer and close the icon on the right.

Hi @qyjs, we are following the styles of Ant Design Drawer. A workaround for your case can be implementing your own styles through `nzTitle` api.