docs(module:tooltip): fix typo
NG-ZORRO/ng-zorro-antd pull request #7306
Opened 2022-03-09 09:34 UTC by yutao331763646

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2022-03-09 09:34 UTC, yutao331763646 commented
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/27717350/157413869-d67875e5-7c56-4a33-81f2-75923875e59c.png">
与antd表现不一致

2022-03-09 12:38 UTC, wendellhu95 approved these changes
LGTM. Thanks!

2022-03-10 08:38 UTC, yutao331763646 commented
目前的问题，如下图，当下拉选项超出屏幕时，会被遮挡
<img width="445" alt="image" src="https://user-images.githubusercontent.com/27717350/157621556-fe2f80e5-00c2-41e6-9513-c1eae9483f9b.png">

2022-03-10 08:39 UTC, yutao331763646 commented
修改之后：自动调整位置，使其剧中，和antd react体验保持一致，如下图
<img width="388" alt="image" src="https://user-images.githubusercontent.com/27717350/157621758-4d7b4579-3254-4a67-be5f-13704ce399f3.png">

2022-03-10 09:04 UTC, simplejason commented on components/cascader/cascader.component.ts
> +    }, 10);
Avoid to use `setTimeout()`, check function `reposition` in this file

2022-03-10 09:05 UTC, simplejason requested changes

2022-03-10 09:05 UTC, simplejason commented on components/cascader/cascader.component.ts
> +    }, 10);
Avoid to use `setTimeout()`, check function `reposition` in this file

2022-03-10 10:29 UTC, yutao331763646 commented on components/cascader/cascader.component.ts
> +    }, 10);
我这个场景，是每次点击cascader-li时，右边的cascader-ul渲染出来，再重新调整overlay的位置，promise.resolve只能保证有新的变更时执行，但是我需要拿到变更的结果，所以用了detectChanges，同步跑了一次check，再更新位置 。@simplejason

2022-03-13 08:09 UTC, wendellhu95 commented on components/cascader/cascader.component.ts
> +    console.log(this.inSearchingMode);
Please clean up console.log.

2022-03-14 03:20 UTC, yutao331763646 commented on components/cascader/cascader.component.ts
> +    console.log(this.inSearchingMode);
Sorry, everything is ok. @wendellhu95

2022-04-21 07:11 UTC, simplejason approved these changes
LGTM

2022-04-21 07:14 UTC, merged