feat(module:image): nz-image add press `left` or `right` to switch image
NG-ZORRO/ng-zorro-antd pull request #7321
Opened 2022-03-14 06:57 UTC by amoycode

The nz-image add nzEnableLeftRightArrow to support press `left` or `right` to switch image

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2022-03-16 11:09 UTC, cipchk requested changes
建议同时对单元测试的覆盖。

2022-03-16 11:09 UTC, cipchk commented on components/image/image-preview-ref.ts
> +    overlayRef
建议与 `ESCAPE` 逻辑处理在同一个订阅当中。

2022-03-16 11:09 UTC, cipchk commented on components/image/image-preview-options.ts
> +  nzEnableLeftRightArrow?: boolean = true;
不建议增加该字段， `nzKeyboard` 本身就是表示是否键盘操作，这里增加一个额外字段，倘若鼠标中间键切换时是不是也应该有另一个字段；因此容易产生歧义，以其如此，不如直接使用 `nzKeyboard` 来判断足够了。

2022-03-24 06:01 UTC, cipchk approved these changes
LGTM

2022-03-31 14:20 UTC, stygian-desolator commented
LGTM

2022-04-20 14:08 UTC, merged