chore: add  to support css variable
NG-ZORRO/ng-zorro-antd pull request #7436
Opened 2022-05-16 11:14 UTC by simplejason

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2022-05-17 11:32 UTC, hullis approved these changes
LGTM. Glad to see it get landed!

2022-05-17 11:33 UTC, hullis commented on docs/customize-theme-variable.zh-CN.md
> +import { ConfigProvider } from 'antd';
antd

2022-05-17 11:34 UTC, hullis requested changes
Docs are for the React version.

2022-05-18 06:37 UTC, simplejason commented on docs/customize-theme-variable.zh-CN.md
> +import { ConfigProvider } from 'antd';
已经支持 nzConfigService，还有些测试我补齐一下

2022-05-24 02:03 UTC, yangjunhan approved these changes
LGTM

2022-05-24 06:26 UTC, merged