fix(module:tabs): fix selected index not update if new tab added after navigated
NG-ZORRO/ng-zorro-antd pull request #7649
Opened 2022-09-27 05:13 UTC by laggage

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
navigate with `await router.navigate(...)` to a new position and add update tabs bounded to the `nz-tab`, active tab not updated

Issue Number: N/A

## What is the new behavior?
navigate with `await router.navigate(...)` to a new position and add update tabs bounded to the `nz-tab`, active tab will be updated

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
The example above may look meaningless, however, there is a condition that a link tab is guarded by a feature flag, and so the tab can only be added after the route navigated, in this case, selected tab won't update properly

2023-03-04 13:49 UTC, laggage commented
I have update the pr

Please take a look when you have time, let me know if there any problem in the code, i will try fix it as soon a i can

2023-05-25 03:41 UTC, laggage commented
Hey, I'm looking forward to your review :) @hsuanxyz 

This will fix #4773, once merged, we can remove the hack code in our project that using the router tab

Please take a look when you are free

2025-01-28 17:57 UTC, tonybrasunas-greenlots commented
Any further progress on this? It's been nearly two years, and we're still seeing the Menu default to the first page on page refresh.

2025-02-21 05:49 UTC, Laffery requested changes
Please rebase from master

2025-03-26 03:33 UTC, laggage commented
> Please rebase from master

Updated

2025-03-26 06:22 UTC, laggage commented
Here is a demo video may better explain the idea

https://github.com/user-attachments/assets/31a1a96d-92ed-4693-83ce-8b4f6e6d6772


> PS: have no idea why why the preview protal didn't take effect after force push and the success of build_site

2025-03-26 06:58 UTC, Laffery requested changes

2025-03-26 06:58 UTC, Laffery commented on components/tabs/demo/link-router.ts
> +      <nz-tab *ngFor="let tab of dynamicTabs">
使用 `@for`

2025-03-26 06:58 UTC, Laffery commented on components/tabs/tabset.component.spec.ts
> +      // tabs = fixture.debugElement.query(By.directive(NzTabSetComponent));
清理注释

2025-03-26 06:58 UTC, Laffery commented on components/tabs/tabset.component.spec.ts
> +      <nz-tab *ngFor="let tab of tabs">
使用 `@for`

2025-03-26 07:28 UTC, Laffery approved these changes
LGTM

2025-03-26 09:06 UTC, merged