feat(module:cron-expression): add cron-expression component
NG-ZORRO/ng-zorro-antd pull request #7677
Opened 2022-10-12 12:37 UTC by OriginRing

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2022-10-13 02:31 UTC, simplejason requested changes

2022-10-13 02:31 UTC, simplejason commented on components/i18n/nz-i18n.interface.ts
> +  cronMore3: string;
1、2、3 这种命名不要有，看下有没有语义化的描述

2022-10-13 06:13 UTC, hsuanxyz requested changes

2022-10-13 06:13 UTC, hsuanxyz commented on components/components.less
> +@import './cron-expression/style/entry';
```suggestion
@import './cron-expression/style/entry.less';
```

2022-10-13 06:13 UTC, hsuanxyz commented on components/cron-expression/cron-expression-specialized.component.ts
> +                <input nz-input formControlName="minute" id="minute" name="minute" />
Are there `id`(s) here required? If so, use the dynamic `id`.

2022-10-13 06:13 UTC, hsuanxyz commented on components/cron-expression/cron-expression-specialized.component.ts
> +  onChange: any = () => {};
```suggestion
  onChange: SafeAny = () => {};
```

2022-10-13 06:13 UTC, hsuanxyz commented on components/cron-expression/cron-expression-specialized.component.ts
> +  registerOnChange(fn: any): void {
```suggestion
  registerOnChange(fn: SafeAny): void {
```

2022-10-13 06:13 UTC, hsuanxyz commented on components/cron-expression/cron-expression-specialized.component.ts
> +  registerOnTouched(fn: any): void {
```suggestion
  registerOnTouched(fn: SafeAny): void {
```

2022-10-13 06:13 UTC, hsuanxyz commented on components/cron-expression/cron-expression.component.ts
> +  onChange: any = () => {};
```suggestion
  onChange: SafeAny = () => {};
```

2022-10-13 06:13 UTC, hsuanxyz commented on components/cron-expression/cron-expression.component.ts
> +  }
```suggestion
  registerOnChange(fn: SafeAny): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: SafeAny): void {
    this.onTouch = fn;
  }
```

2022-10-20 09:49 UTC, hsuanxyz approved these changes
LGTM

2022-10-20 10:06 UTC, hsuanxyz commented on components/cron-expression/cron-expression.component.ts
> +              <a (click)="loadDate()">···</a>
```suggestion
              <ul class="ant-cron-expression-preview">
                <li *ngFor="let dateItem of nextTimeList">
                  {{ dateItem | date: 'YYYY-MM-dd HH:mm:ss' }}
                </li>
                 <li><a (click)="loadDate()">···</a></li>
              </ul>
             
```

2022-11-07 02:28 UTC, simplejason approved these changes
LGTM

2022-11-07 02:29 UTC, merged