feat(module:watermark): add watermark component
NG-ZORRO/ng-zorro-antd pull request #7857
Opened 2023-03-03 01:54 UTC by OriginRing

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2023-03-08 10:22 UTC, hsuanxyz requested changes

2023-03-08 10:22 UTC, hsuanxyz commented on components/water-mark/demo/custom.ts
> +  offset!: [number, number];
```suggestion
  offset: [number, number];
```

2023-03-08 10:22 UTC, hsuanxyz commented on components/water-mark/water-mark.component.ts
> +    <div style="position: relative;" #watermark>
直接写在 host 上

2023-03-08 10:22 UTC, hsuanxyz commented on components/water-mark/water-mark.component.ts
> +  @ViewChild('watermark', { static: false }) containerElement!: ElementRef<HTMLDivElement>;
直接用 host

2023-03-08 10:22 UTC, hsuanxyz commented on components/water-mark/water-mark.component.ts
> +  waterMarkElement: HTMLDivElement = document.createElement('div');
用  `import { DOCUMENT } from '@angular/common';`

2023-04-02 08:02 UTC, simplejason approved these changes
LGTM

2023-04-02 08:02 UTC, merged