feat(module:float-button): add float-button component
NG-ZORRO/ng-zorro-antd pull request #7884
Opened 2023-03-24 04:07 UTC by OriginRing

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2024-01-15 06:09 UTC, NRaf commented
Hi,

Just came across this feature in the React branch and noticed it's missing from ng-zorro. Any idea on when this will be merged in?

2024-08-31 15:42 UTC, Laffery requested changes

2024-08-31 15:42 UTC, Laffery commented on components/float-button/demo/group-menu.md
> +设置 `nzTrigger` 属性即可开启菜单模式。提供 hover 和 click 两种触发方式。
```suggestion
设置 `nzTrigger` 属性即可开启菜单模式。提供 `hover` 和 `click` 两种触发方式。
```

2024-08-31 15:42 UTC, Laffery commented on components/float-button/demo/group.md
> +When multiple buttons are used together, `nz-float-button-group` is recommended. By setting `nzShape` of FloatButtonGroup, you can change the shape of group.
FloatButtonGroup 是 react 版中的组件， 这里表述应为 zorro 中的组件

2024-08-31 15:42 UTC, Laffery commented on components/float-button/doc/index.en-US.md
> +tag: 18.1.0
18.2.0

2024-08-31 15:42 UTC, Laffery commented on components/float-button/float-button-content.component.ts
> +  @Input() nzDescription: TemplateRef<void> | null = null;
支持直接传 string 吗

2024-08-31 15:42 UTC, Laffery commented on components/float-button/float-button-group.component.ts
> +    @Optional() private directionality: Directionality,
写法上参考 #8567 已经将所有可选写法都改成用 inject 的方式注入

2024-08-31 15:42 UTC, Laffery commented on components/float-button/float-button.component.ts
> +  detectChanges(): void {
这个方法没看到用处

2024-10-05 00:28 UTC, Laffery approved these changes
LGTM

2024-11-19 05:49 UTC, Laffery requested changes

2024-11-19 05:49 UTC, Laffery commented on scripts/site/template/ng-zorro-antd.module.template.ts
Please rebase from master, this file had been removed

2024-11-19 05:49 UTC, Laffery commented on components/float-button/doc/index.zh-CN.md
> +tag: 18.2.0
```suggestion
tag: 19.0.0
```

2024-11-19 05:49 UTC, Laffery commented on components/float-button/doc/index.en-US.md
> +tag: 18.2.0
```suggestion
tag: 19.0.0
```

2024-11-20 10:10 UTC, merged

2024-11-25 21:26 UTC, lppedd commented on components/back-top/doc/index.en-US.md
> +* Note: This component will be removed later. Please use `<nz-float-button-top></nz-float-button-top>` in the FloatButton component.
Just wondering, does that mean the backtop component is to be considered deprecated?  
Is it in preparation for Ant Design 5?