feat(module:tag): borderless mode
NG-ZORRO/ng-zorro-antd pull request #8320
Opened 2023-12-23 12:08 UTC by ParsaArvanehPA

## PR Checklist
Please check if your PR fulfills the following requirements:

- [✔] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✔] Tests for the changes have been added (for bug fixes / features)
- [✔] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[✔] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Ant design provides a [borderless mode](https://ant.design/components/tag) for its tag component, which is not available in ng-zorro.

## What is the new behavior?
Implemented borderless mode for tag component.

## Does this PR introduce a breaking change?
```
[ ] Yes
[✔] No
```

## Other information

2023-12-23 14:31 UTC, Nicoss54 requested changes
make pass the linter

2023-12-25 14:09 UTC, ParsaArvanehPA commented
> make pass the linter

Thank you for checking my pr.
Linter problems are now fixed.

2023-12-29 08:53 UTC, Nicoss54 approved these changes

2024-01-17 08:44 UTC, OriginRing approved these changes

2024-01-17 08:48 UTC, merged