fix(module:tree-select): fix search box exception when Chinese search
NG-ZORRO/ng-zorro-antd pull request #8324
Opened 2023-12-26 08:53 UTC by EnochGao

fix bug: #8165

2024-01-10 09:56 UTC, Nicoss54 commented
Hi @EnochGao thanks a lot fot this PR, could you please provide the tests for the code added :) 

Thanks in advance :)

2024-01-10 09:56 UTC, Nicoss54 requested changes
Hi @EnochGao thanks a lot fot this PR, could you please provide the tests for the code added :)

Thanks in advance :)

2024-01-16 02:48 UTC, EnochGao commented
> Hi @EnochGao thanks a lot fot this PR, could you please provide the tests for the code added :)
> 
> Thanks in advance :)

Kindly verify it

2024-01-16 08:22 UTC, Nicoss54 commented on components/tree-select/tree-select.spec.ts
> +describe('nz-tree-select component', () => {
suggestion: all the test are correct, but please move them into the basics section please

2024-01-17 08:09 UTC, Nicoss54 approved these changes

2024-01-17 08:09 UTC, Nicoss54 commented
LGTM

2024-01-22 02:08 UTC, merged