fix(module:avatar): avatar not re-scaling properly
NG-ZORRO/ng-zorro-antd pull request #8365
Opened 2024-01-19 14:21 UTC by ParsaArvanehPA

## PR Checklist
Please check if your PR fulfills the following requirements:

- [✔] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✔] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[✔] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The scaling of the avatar component was previously performed by a method named `notifyCalc`. This method used a setTimeout function to delay the scaling function for 4 milliseconds, ensuring that the avatar component was fully rendered and ready to be scaled.

However, this caused a problem when the avatar component was used within components that had opening animation effects, as the avatar component would have an incorrect width. The avatar component required more than 4 milliseconds in these cases to reach its sinalsize, and calling the scaling function, `calcStringSize`, too early would result in incorrect scale values for the avatar component.

Issue Number: #8363 

## What is the new behavior?
Calling `calcStringSize` after avatar component is fully rendered.

## Does this PR introduce a breaking change?
```
[ ] Yes
[✔] No
```

## Other information

2024-01-22 22:22 UTC, Nicoss54 requested changes
@OriginRing build and test schematics job failed sinced the last merged.

This PR fixed the issue: #8367

@ParsaArvanehPA when #8367 will be merged, please rebase to make the build and test schematics pass, then LGTM

2024-01-23 09:25 UTC, Nicoss54 commented
@ParsaArvanehPA could you please rebase the branch, to have the fix for the pipeline and then see if all the job passed

2024-01-23 10:23 UTC, ParsaArvanehPA commented
> @ParsaArvanehPA could you please rebase the branch, to have the fix for the pipeline and then see if all the job passed

@Nicoss54 Yeah sure

2024-01-23 11:12 UTC, Nicoss54 reviewed
LGTM

2024-01-23 11:13 UTC, Nicoss54 approved these changes

2024-03-11 14:05 UTC, merged