Feature/radio selection in tables
NG-ZORRO/ng-zorro-antd pull request #8456
Opened 2024-03-20 23:24 UTC by ParsaArvanehPA

## PR Checklist
Please check if your PR fulfills the following requirements:

- [✔] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✔] Tests for the changes have been added (for bug fixes / features)
- [✔] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[✔] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
In [Ant design](https://ant.design/components/table#components-table-demo-row-selection) it is possible to have both `checkbox` and `radio` as selection type for columns; meanwhile we only support `checkbox` selection type.

Issue Number: #8029 

## What is the new behavior?
Now supports radio selection type.

## Does this PR introduce a breaking change?
```
[ ] Yes
[✔] No
```

## Other information

2024-05-31 06:11 UTC, Laffery requested changes

2024-05-31 06:11 UTC, Laffery commented on components/table/doc/index.zh-CN.md
> +无线电财产
translation erorr :)

--> 单选属性

2024-07-17 10:03 UTC, ParsaArvanehPA commented on components/table/demo/selection.md
> +order: 2
This happens to be the only one with order value of 2; first order is 0, then jumps to 3.

2024-07-17 10:11 UTC, ParsaArvanehPA commented on components/table/doc/index.en-US.md
> +radio property
fixed.

2024-07-17 10:11 UTC, ParsaArvanehPA commented on components/table/src/cell/td-addon.component.ts
> +        this.nzShowRadio = true;
yeah you are right, done.

2024-07-17 10:16 UTC, ParsaArvanehPA commented on components/table/doc/index.zh-CN.md
> +无线电财产
done :)

2024-07-17 10:36 UTC, ParsaArvanehPA commented
Your requested changes are made, could you please check it again?
@Laffery

2024-08-04 10:48 UTC, ParsaArvanehPA commented
@Laffery 
Don't know why if failed the second time i pushed last time :)
now is fixed 🙃

2024-10-05 06:51 UTC, closed without merging

2024-10-05 06:53 UTC, ParsaArvanehPA commented
closed due to inactivity on my part, re-opened in a new pr