feat(module:date-picker): quarter selection of date picker(#7818,#7380)
NG-ZORRO/ng-zorro-antd pull request #8478
Opened 2024-04-04 11:59 UTC by m310851010

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7818, #7380

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2024-04-05 06:32 UTC, HyperLife1119 commented on components/i18n/date-helper.service.ts
> +  }
使用 date-fns 的 getQuarter 替代

2024-04-05 08:20 UTC, HyperLife1119 commented on components/i18n/date-helper.service.ts
> +  }
简化正则表达式，并添加一些注释：

```ts
// Q Pattern format compatible with date-fns (quarter).
return dateStr
  // Match Q+ outside of brackets, then replace it with the specified quarterly format
  .replace(/Q+(?![^\[]*])/g, match => record[match] ?? quarter)
  // Match the Q+ surrounded by bracket, then remove bracket.
  .replace(/\[(Q+)]/g, '$1');
```

2024-04-08 02:34 UTC, HyperLife1119 commented on components/date-picker/demo/date-render.ts
> +      <div class="ant-picker-cell-inner" [class.border]="current.getDate() === 1"> {{ current.getDate() }} </div>
```suggestion
      <div class="ant-picker-cell-inner" [class.border]="current.getDate() === 1">{{ current.getDate() }}</div>
```

2024-04-08 02:41 UTC, HyperLife1119 commented on components/i18n/date-helper.service.ts
> +  }
可以为新增的 Q 格式添加单元测试 :)

2024-04-11 10:39 UTC, HyperLife1119 approved these changes
LGTM

2024-04-11 10:42 UTC, HyperLife1119 commented
@Nicoss54 Can you review this PR together? :)

2024-04-11 13:56 UTC, Nicoss54 commented
> @Nicoss54 Can you review this PR together? :)

of course i will review it today or tomorrow morning :)

2024-04-22 16:35 UTC, Nicoss54 approved these changes
LGTM

2024-05-31 05:16 UTC, Laffery commented on components/i18n/languages/zh_TW.ts
> +      rangeQuarterPlaceholder: ['開始季度', '開始季度'],
```diff
- rangeQuarterPlaceholder: ['開始季度', '開始季度'],
+ rangeQuarterPlaceholder: ['開始季度', '結束季度'],
```

2024-05-31 05:16 UTC, Laffery commented on components/i18n/languages/zh_HK.ts
> +      rangeQuarterPlaceholder: ['開始季度', '開始季度'],
```diff
- rangeQuarterPlaceholder: ['開始季度', '開始季度'],
+ rangeQuarterPlaceholder: ['開始季度', '結束季度'],
```

2024-05-31 05:23 UTC, Laffery requested changes
Hi there 👋, thank your very much for contributing such fancy feature to ng-zorro, there are some issues should be fixed :)

2024-06-03 04:45 UTC, Laffery approved these changes
LGTM

2024-06-03 04:59 UTC, merged