refactor(style): migrate from @functions to @plugin usage
NG-ZORRO/ng-zorro-antd pull request #8552
Opened 2024-05-27 06:52 UTC by HyperLife1119

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information

2024-05-28 17:39 UTC, HyperLife1119 commented
<img width="505" alt="image" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/41798664/3fa860fc-f6d4-43df-9e66-3750fd86071d">

需要在 CodeFactor 配置中忽略 components/style/color/tinycolor2.js 文件。

2024-05-29 00:45 UTC, Laffery requested changes

2024-05-29 00:45 UTC, Laffery commented on scripts/site/generate-theme.js
#8545 is merged, please rebase

2024-05-29 01:05 UTC, HyperLife1119 commented on scripts/site/generate-theme.js
Done.

2024-05-30 00:42 UTC, Laffery approved these changes
LGTM. I'll try to configure the codefactor settings to ignore tinycolor2.js

2024-05-30 05:04 UTC, merged

2024-07-17 03:40 UTC, Laffery commented
@HyperLife1119 
我在使用[动态切换主题](https://ng.ant.design/docs/customize-theme/zh#%E5%8A%A8%E6%80%81%E5%88%87%E6%8D%A2%E4%B8%BB%E9%A2%98) 时遇问题，看起来可能和这个 pr 有关。

reproduction link -> https://github.com/Laffery/nz-theme-issue

在 https://github.com/Laffery/nz-theme-issue/blob/main/src/app/pages/welcome/welcome.component.less#L10 中使用了zorro 内置变量 `@gold-3`，运行 `npm start` 抛错如下:

<img width="945" alt="image" src="https://github.com/user-attachments/assets/4e475797-a1ce-4fd4-8a8c-806b3077c15c">

断点调试定位到抛错位置在 https://github.com/less/less.js/blob/master/packages/less/src/less/functions/color.js#L435
![image](https://github.com/user-attachments/assets/c49d45de-dfad-4788-a97b-6819cad06cb0)

如果有时间请看下这个问题，期待和你一起探讨！

2024-07-17 07:31 UTC, HyperLife1119 commented
我试了一下，看起来似乎是因为在 mixin 内部使用 import，会影响 @plugin 的加载，我在顶部添加一个 colorPalette.less 的导入就可以解决这个问题了：

```less
@import '../../../node_modules/ng-zorro-antd/src/style/color/colorPalette.less';

.themeMixin(@rules) {
  html {
    &.default {
      @import './default.less';
      @rules();
    }
    &.dark {
      @import './dark.less';
      @rules();
    }
  }
}

```

2024-07-17 08:43 UTC, Laffery commented
> 或者说必须在顶部导入 antd 的某个 theme，它们已经包含了那几个 plugins，或者直接在顶部导入 plugin 对应的 less 文件。🧐
动态主题场景下可能不太会在顶部就导入某个 theme，目前看最好就是在顶部导入 plugin。
我觉得可以在 [动态切换主题](https://ng.ant.design/docs/customize-theme/zh#%E5%8A%A8%E6%80%81%E5%88%87%E6%8D%A2%E4%B8%BB%E9%A2%98) 文档里补充下说明