build: remove-custom-webpack
NG-ZORRO/ng-zorro-antd pull request #8553
Opened 2024-05-27 08:28 UTC by HyperLife1119

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2024-05-27 14:28 UTC, HyperLife1119 commented on components/style/testing.less
> +// @import './variable.less';
当测试中需要导入样式时，必须首先导入该样式文件。该文件用于在测试中填充 @root-entry-name 变量。

2024-05-30 05:07 UTC, Laffery requested changes
previous pr  #8552 was merged, please rebase

2024-05-30 11:58 UTC, Laffery commented on components/style/testing.less
> +// @import './variable.less';
最后一行可以删掉吧👀

2024-05-30 12:30 UTC, HyperLife1119 commented on components/style/testing.less
> +// @import './variable.less';
可以了

2024-05-31 01:46 UTC, Laffery approved these changes
LGTM

2024-05-31 04:15 UTC, merged