refactor(module:docs): refactor docs to standalone module
NG-ZORRO/ng-zorro-antd pull request #8647
Opened 2024-07-22 00:21 UTC by Laffery

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2024-07-22 04:05 UTC, Laffery commented on scripts/site/_site/doc/app/app.config.server.ts
generated from `ng new --ssr` and extended from the original `app.server.module.ts` file

2024-07-22 04:07 UTC, Laffery commented on scripts/site/_site/doc/app/app.routes.ts
> -  { path: 'demo', component: DEMOComponent },
Will be redirected to `/introduce/zh` when visiting `/demo`, I wonder whether there are developer take advantage of this or not, so removed

2024-07-23 07:00 UTC, HyperLife1119 requested changes
Nice job!

2024-07-23 07:44 UTC, Laffery commented on scripts/site/_site/doc/app/app.config.server.ts
> +    importProvidersFrom(NzIconModule.forRoot(icons))
You are RIGHT
我印象中之前支持了 provideNzConfig 之后，我就感觉 icons 这里的用法有点过时了

2024-07-23 08:12 UTC, Laffery commented on scripts/site/_site/doc/app/app.component.ts
> +      this.router.navigate(['docs', 'introduce', 'zh']).then();
IDE warning 提示，不影响代码逻辑
<img width="527" alt="image" src="https://github.com/user-attachments/assets/5a497cbb-da9a-486e-8060-07447a181c83">

2024-07-23 09:30 UTC, HyperLife1119 approved these changes
LGTM. Nice Job!

2024-07-23 09:31 UTC, merged