refactor(module:tree,tree-select,tree-view): migrate to new control flow
NG-ZORRO/ng-zorro-antd pull request #8688
Opened 2024-08-07 09:46 UTC by HyperLife1119

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2024-08-09 22:27 UTC, Laffery commented on components/tree-view/indent.ts
> +  imports: [],
remove this line

2024-08-09 22:30 UTC, Laffery commented on components/tree/tree-indent.component.ts
> +  imports: [],
```suggestion

```

2024-08-09 22:31 UTC, Laffery commented on components/tree-view/indent.ts
> +  imports: [],
```suggestion

```

2024-08-09 22:34 UTC, Laffery commented on components/tree/tree-node-title.component.ts
> +            @if (icon) {
can be removed because `icon && showIcon` is declared in the upper scope

2024-08-09 22:42 UTC, Laffery commented on components/tree/tree.component.ts
> +          @for (node of nzFlattenNodes; track trackByFlattenNode($index, node)) {
```suggestion
          @for (node of nzFlattenNodes; track node.key)) {
```

2024-08-09 22:44 UTC, Laffery requested changes
some comments to be resolved

2024-08-13 10:48 UTC, HyperLife1119 commented on components/tree/tree.component.ts
> +          @for (node of nzFlattenNodes; track trackByFlattenNode($index, node)) {
因为 cdk 虚拟滚动有在使用这个 trackByFlattenNode 函数，所以这里的 @for track 也继续使用了，保持一致

2024-08-16 15:25 UTC, Laffery approved these changes
LGTM

2024-08-16 15:26 UTC, merged