feat(module:transfer): use nzOneWay to make Transfer the one way style
NG-ZORRO/ng-zorro-antd pull request #8717
Opened 2024-08-28 04:21 UTC by OriginRing

fix: #8643

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2024-08-28 08:54 UTC, HyperLife1119 commented on components/transfer/transfer-list.component.ts
> +  @Input() nzOneWay: boolean = false;
```suggestion
  @Input() oneWay: boolean = false;
```

2024-08-28 09:59 UTC, OriginRing commented on components/transfer/transfer-list.component.ts
> +  @Input() nzOneWay: boolean = false;
已修改

2024-08-29 01:54 UTC, HyperLife1119 approved these changes
LGTM

2024-08-31 14:53 UTC, Laffery requested changes

2024-08-31 14:53 UTC, Laffery commented on components/transfer/demo/on-way.ts
> +  selector: 'nz-demo-transfer-on-way',
`on-way` -> `one-way`

2024-08-31 14:53 UTC, Laffery commented on components/transfer/transfer-list.component.ts
> +    NzButtonComponent
Remove unused NzButtonModule

2024-09-02 02:23 UTC, OriginRing commented on components/transfer/transfer-list.component.ts
> +    NzButtonComponent
Corrected

2024-09-03 06:20 UTC, HyperLife1119 commented
Please fix the test :)

2024-11-19 05:35 UTC, Laffery approved these changes
LGTM

2024-11-20 13:53 UTC, merged