fix(module: select): multiple select cause switch size flash when init
NG-ZORRO/ng-zorro-antd pull request #8851
Opened 2024-11-01 03:04 UTC by Douc1998

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [#8847](https://github.com/NG-ZORRO/ng-zorro-antd/issues/8847)

## What is the new behavior?

当 select 的 nzMode 设为 multiple 或 tags 且 switch 的 nzSize 设为 small 时，switch 组件初始化时不再出现大小闪烁现象（由 default 变为 small）

When nzMode of select is multiple or tags, and nzSize of switch is small, the size flashing (change from default to small) of switch no longer occurs at initialization.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2024-11-01 09:41 UTC, Laffery requested changes
Hi there 👋, thanks for your first contribution to ng-zorro !

What about wrapping the `regAnimFrame` in the `syncMirrorWidth` method instead?

```ts
syncMirrorWidth(): void {
	reqAnimFrame(() => {
		// ...
	});
}
```

2024-11-01 09:45 UTC, Laffery commented
Further more, even though we have encapsulated the `reqAnimFrame` method to polyfill `requestAnimationFrame` in various browser, there are only a few of components had taken advantage of this method.
It would be great to pull a request to upgrade these usage for `reqAnimFrame` if you like !

2024-11-01 10:00 UTC, WwwHhhYran commented
> Hi there 👋, thanks for your first contribution to ng-zorro !
> 
> What about wrapping the `regAnimFrame` in the `syncMirrorWidth` method instead?
> 
> ```ts
> syncMirrorWidth(): void {
> 	reqAnimFrame(() => {
> 		// ...
> 	});
> }
> ```

Thank you for your suggestion. Obviously, this is a more elegant way of coding. I have made the necessary modifications, thanks very much !

2024-11-01 10:04 UTC, WwwHhhYran commented
> Further more, even though we have encapsulated the `reqAnimFrame` method to polyfill `requestAnimationFrame` in various browser, there are only a few of components had taken advantage of this method. It would be great to pull a request to upgrade these usage for `reqAnimFrame` if you like !

I'm willing and will try my best to do that 🤝

2024-11-07 02:36 UTC, WwwHhhYran reviewed
done

2024-11-07 08:30 UTC, Laffery approved these changes
LGTM

2024-11-07 08:43 UTC, merged