chore: bump angular to v19
NG-ZORRO/ng-zorro-antd pull request #8905
Opened 2024-12-02 07:47 UTC by Laffery

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

2024-12-02 14:07 UTC, HyperLife1119 commented
As far as I know, ngx-quicklink already [supports v19](https://github.com/mgechev/ngx-quicklink/commit/82eeebc1471e5a849d75a0dbed332301a954ba6d), but I still recommend to remove it completely to reduce dependencies, because I don't think it will be much of a benefit for a documentation site, the bundle size of the documentation pages is not that big, and no additional preloading strategy is needed.

2024-12-02 14:11 UTC, HyperLife1119 commented
Since this is a "huge" PR, I recommend leaving it until the end :)

2024-12-03 00:12 UTC, Laffery commented
> As far as I know, ngx-quicklink already [supports v19](https://github.com/mgechev/ngx-quicklink/commit/82eeebc1471e5a849d75a0dbed332301a954ba6d), but I would still recommend removing it altogether and thus reducing the number of dependencies, as I don't think it's very beneficial to the documentation site, and the bundle size of the documentation pages isn't large enough to require an additional preloading strategy. WDYT?

Agree with you. The repo of `ngx-quicklink` is not quite activated, the package also brings us some License Compiliant issues. We can just remove it because its few benifit

2024-12-03 00:13 UTC, Laffery commented
> As far as I know, ngx-quicklink already [supports v19](https://github.com/mgechev/ngx-quicklink/commit/82eeebc1471e5a849d75a0dbed332301a954ba6d), but I would still recommend removing it altogether and thus reducing the number of dependencies, as I don't think it's very beneficial to the documentation site, and the bundle size of the documentation pages isn't large enough to require an additional preloading strategy. WDYT?

Agree with you. The repo of `ngx-quicklink` is not quite activated, the package also brings us some License Compiliant issues. We can just remove it because its few benifit

2024-12-03 01:29 UTC, Laffery commented on .eslintrc.js
> +        '@typescript-eslint/no-wrapper-object-types': 'error',
ref https://typescript-eslint.io/blog/announcing-typescript-eslint-v8#replacement-of-ban-types

2024-12-03 08:04 UTC, HyperLife1119 requested changes

2024-12-03 08:04 UTC, HyperLife1119 commented on scripts/schematics/demo2schematics.ts
> +    ;
```ts
 });
```

2024-12-03 09:16 UTC, Laffery commented on docs/universal.zh-CN.md
同意，之前我考虑重新写一篇基于 `@angular/ssr` 的文档，但其实在服务端渲染中 ng-zorro 并没有特别需要配置的，所以可以移除

2024-12-05 08:29 UTC, HyperLife1119 approved these changes
LGTM

2024-12-05 08:35 UTC, merged