feat(module:checkbox): redesign the checkbox group component
NG-ZORRO/ng-zorro-antd pull request #8932
Opened 2024-12-14 10:10 UTC by HyperLife1119

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

2024-12-14 14:06 UTC, Laffery requested changes

2024-12-14 14:06 UTC, Laffery commented on components/checkbox/checkbox-group.component.ts
>  export interface NzCheckBoxOptionInterface {
我们可以在 checkbox 文档的 API 部分将 `NzCheckBoxOptionInterface` Interface 定义贴上

2024-12-14 17:47 UTC, HyperLife1119 commented on components/checkbox/checkbox-group.component.ts
> +export interface NzCheckBoxOption {
NzCheckBoxOption or NzCheckboxOption? WDYT?

2024-12-14 22:34 UTC, Laffery commented on components/checkbox/checkbox-group.component.ts
> +export interface NzCheckBoxOption {
NzCheckboxOption

2024-12-15 08:16 UTC, Laffery approved these changes
LGTM

2024-12-15 08:16 UTC, merged